version: "3.5"

services:
  homepage2:
    build: .
    container_name: homepage2
    image: homepage2
    expose:
      - "10002"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: www.peixe.eu.org, peixe.eu.org
      LETSENCRYPT_HOST: www.peixe.eu.org, peixe.eu.org
      LETSENCRYPT_EMAIL: admin@domain.com
      LETSENCRYPT_TEST: "true"
networks:
  default:
    external:
      name: webproxy
