version: "3.6"
services:
  homepage2:
    image: homepage2
    networks:
      - traefik_proxy
    deploy:
      # replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.3"
          memory: 60M
      labels:
        - "traefik.enable=true"
        - "traefik.port=10002" 
        - "traefik.protocol=http,https"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:peixe.eu.org,www.peixe.eu.org"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend=homepage2"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.loadbalancer.method=drr"
        # - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.headers.STSSeconds=315360000"
        - "traefik.frontend.headers.browserXSSFilter=true"
        - "traefik.frontend.headers.contentTypeNosniff=true"
        - "traefik.frontend.headers.forceSTSHeader=true"
        # - "traefik.frontend.headers.SSLHost=example.com"
        # - "traefik.frontend.headers.STSIncludeSubdomains=true"
        - "traefik.frontend.headers.STSPreload=true"
        - "traefik.frontend.headers.frameDeny=true"

networks:
  traefik_proxy:
    driver: overlay
    external: true

