version: "3.6"
services:
  homepage1:
    image: homepage1
    networks:
      - webgateway
    restart: on-failure  
    environment:
      - COMPOSE_PROJECT_NAME = "homepage1"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"  
      - "traefik.frontend.rule=Host:adolfo-peixinho.eu.org,www.adolfo-peixinho.eu.org"
      - "traefik.backend=homepage1"
      - "traefik.backend.loadbalancer.method=drr"
      # - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.port=10001"
      - "traefik.docker.network=webgateway"

networks:
  webgateway:
    external: true