version: "3.5"

services:
  homepage1:
    build: .
    container_name: homepage1
    image: homepage1
    expose:
      - "10001"
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: www.adolfo-peixinho.eu.org, adolfo-peixinho.eu.org
      LETSENCRYPT_HOST: www.adolfo-peixinho.eu.org, adolfo-peixinho.eu.org
      LETSENCRYPT_EMAIL: admin@domain.com
      LETSENCRYPT_TEST: "true"
networks:
  default:
    external:
      name: webproxy
